### ISSUE TITLE
Header files needed

### ISSUE THREAD

**Issue by xoox** [olegk0/librklayers#1]
Hello, I'm trying to compile librklayers (needed by xf86-video-fbdev) on Debian jessie with a [Marsboard RK3066](http://marsboard.org/marsboard_rk3066_feature.html)

But some missed header files stop the compiling because of they are symbol links.
Would you please make them publicly available?

Thanks for your wonderful work.

**Comment by olegk0** [comment]
Hello
here https://github.com/olegk0/rk3188-kernel/blob/master/drivers/video/rockchip/out_cache_defs.h
here https://github.com/olegk0/rk3188-kernel/blob/master/drivers/gpu/mali/rk_ump/rk_ump.h
and UMP headers from arm (ump library)

but I have not tested the latest version with rk3066
try https://github.com/olegk0/librklayers/tree/v0.5 or https://github.com/olegk0/librklayers/tree/v0.3
